# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainw.ui',
# licensing of 'mainw.ui' applies.
#
# Created: Tue Jul 21 08:43:02 2020
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 342)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblnombre = QtWidgets.QLabel(self.centralwidget)
        self.lblnombre.setGeometry(QtCore.QRect(240, 90, 381, 16))
        self.lblnombre.setObjectName("lblnombre")
        self.entRuc = QtWidgets.QLineEdit(self.centralwidget)
        self.entRuc.setGeometry(QtCore.QRect(240, 170, 101, 21))
        self.entRuc.setText("")
        self.entRuc.setAlignment(QtCore.Qt.AlignCenter)
        self.entRuc.setObjectName("entRuc")
        self.entSol = QtWidgets.QLineEdit(self.centralwidget)
        self.entSol.setGeometry(QtCore.QRect(380, 170, 111, 21))
        self.entSol.setObjectName("entSol")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 59, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 140, 41, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btnSelect = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelect.setGeometry(QtCore.QRect(20, 80, 211, 31))
        self.btnSelect.setObjectName("btnSelect")
        self.cbEmpresa = QtWidgets.QComboBox(self.centralwidget)
        self.cbEmpresa.setGeometry(QtCore.QRect(20, 30, 211, 32))
        self.cbEmpresa.setObjectName("cbEmpresa")
        self.cbEmpresa.addItem("")
        self.entToken = QtWidgets.QLineEdit(self.centralwidget)
        self.entToken.setGeometry(QtCore.QRect(520, 170, 111, 21))
        self.entToken.setText("")
        self.entToken.setObjectName("entToken")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(230, 30, 113, 32))
        self.btnAdd.setObjectName("btnAdd")
        self.btnValidar = QtWidgets.QPushButton(self.centralwidget)
        self.btnValidar.setGeometry(QtCore.QRect(250, 230, 113, 32))
        self.btnValidar.setObjectName("btnValidar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(410, 150, 59, 16))
        self.label_4.setObjectName("label_4")
        self.cbAnio = QtWidgets.QComboBox(self.centralwidget)
        self.cbAnio.setGeometry(QtCore.QRect(100, 170, 81, 32))
        self.cbAnio.setObjectName("cbAnio")
        self.cbAnio.addItem("")
        self.cbAnio.addItem("")
        self.cbAnio.addItem("")
        self.cbAnio.addItem("")
        self.cbAnio.addItem("")
        self.cbAnio.addItem("")
        self.cbAnio.addItem("")
        self.cbAnio.addItem("")
        self.cbAnio.addItem("")
        self.cbAnio.addItem("")
        self.cbAnio.addItem("")
        self.cbAnio.addItem("")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(530, 150, 81, 20))
        self.label_5.setObjectName("label_5")
        self.cbMes = QtWidgets.QComboBox(self.centralwidget)
        self.cbMes.setGeometry(QtCore.QRect(20, 170, 81, 32))
        self.cbMes.setObjectName("cbMes")
        self.cbMes.addItem("")
        self.cbMes.addItem("")
        self.cbMes.addItem("")
        self.cbMes.addItem("")
        self.cbMes.addItem("")
        self.cbMes.addItem("")
        self.cbMes.addItem("")
        self.cbMes.addItem("")
        self.cbMes.addItem("")
        self.cbMes.addItem("")
        self.cbMes.addItem("")
        self.cbMes.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.lblnombre.setText(QtWidgets.QApplication.translate("MainWindow", "No se ha seleccionado ninguna carpeta", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Periodo", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "RUC", None, -1))
        self.btnSelect.setText(QtWidgets.QApplication.translate("MainWindow", "Seleccionar Carpeta", None, -1))
        self.cbEmpresa.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Seleccionar empresa ...", None, -1))
        self.btnAdd.setText(QtWidgets.QApplication.translate("MainWindow", "Añadir", None, -1))
        self.btnValidar.setText(QtWidgets.QApplication.translate("MainWindow", "Validar", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "client_id", None, -1))
        self.cbAnio.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "2010", None, -1))
        self.cbAnio.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "2011", None, -1))
        self.cbAnio.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2012", None, -1))
        self.cbAnio.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "2013", None, -1))
        self.cbAnio.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "2014", None, -1))
        self.cbAnio.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "2015", None, -1))
        self.cbAnio.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "2016", None, -1))
        self.cbAnio.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "2017", None, -1))
        self.cbAnio.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "2018", None, -1))
        self.cbAnio.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "2019", None, -1))
        self.cbAnio.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "2020", None, -1))
        self.cbAnio.setItemText(11, QtWidgets.QApplication.translate("MainWindow", "2021", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "client_secret", None, -1))
        self.cbMes.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "01", None, -1))
        self.cbMes.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "02", None, -1))
        self.cbMes.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "03", None, -1))
        self.cbMes.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "04", None, -1))
        self.cbMes.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "05", None, -1))
        self.cbMes.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "06", None, -1))
        self.cbMes.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "07", None, -1))
        self.cbMes.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "08", None, -1))
        self.cbMes.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "09", None, -1))
        self.cbMes.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "10", None, -1))
        self.cbMes.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "11", None, -1))
        self.cbMes.setItemText(11, QtWidgets.QApplication.translate("MainWindow", "12", None, -1))

